"""create devices and loans tables

Revision ID: ae2a2c362392
Revises: ev10_users
Create Date: 2026-09-25 22:40:51.746194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2a2c362392'
down_revision: Union[str, Sequence[str], None] = 'ev10_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not sa.inspect(op.get_bind()).has_table('devices'):
        op.create_table('devices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('serial_number', sa.String(), nullable=False),
        sa.Column('device_type', sa.String(), nullable=False),
        sa.Column('brand', sa.String(), nullable=True),
        sa.Column('is_available', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('devices', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_devices_brand'), ['brand'], unique=False)
            batch_op.create_index(batch_op.f('ix_devices_device_type'), ['device_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_devices_is_available'), ['is_available'], unique=False)
            batch_op.create_index(batch_op.f('ix_devices_serial_number'), ['serial_number'], unique=True)

    if not sa.inspect(op.get_bind()).has_table('loans'):
        op.create_table('loans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('loan_date', sa.DateTime(), nullable=False),
        sa.Column('return_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('loans', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_loans_device_id'), ['device_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_loans_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_loans_loan_date'), ['loan_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)
            batch_op.create_index('ix_loans_status_loan_date', ['status', 'loan_date'], unique=False)
            batch_op.create_index('ix_loans_user_device', ['user_id', 'device_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if sa.inspect(op.get_bind()).has_table('loans'):
        with op.batch_alter_table('loans', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_loans_user_id'))
            batch_op.drop_index('ix_loans_user_device')
            batch_op.drop_index('ix_loans_status_loan_date')
            batch_op.drop_index(batch_op.f('ix_loans_status'))
            batch_op.drop_index(batch_op.f('ix_loans_loan_date'))
            batch_op.drop_index(batch_op.f('ix_loans_id'))
            batch_op.drop_index(batch_op.f('ix_loans_device_id'))
        op.drop_table('loans')

    if sa.inspect(op.get_bind()).has_table('devices'):
        with op.batch_alter_table('devices', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_devices_serial_number'))
            batch_op.drop_index(batch_op.f('ix_devices_is_available'))
            batch_op.drop_index(batch_op.f('ix_devices_id'))
            batch_op.drop_index(batch_op.f('ix_devices_device_type'))
            batch_op.drop_index(batch_op.f('ix_devices_brand'))
        op.drop_table('devices')
    # ### end Alembic commands ###
